Refactor plant inversion feedforward, enhancements to docs, and add LTV Unicycle controller tests.
mcm001/allwpilib pull request #18
Opened 2020-06-15 09:58 UTC by cttdev

2020-06-15 23:14 UTC, mcm001 commented
@calcmogul

2020-06-16 00:03 UTC, calcmogul requested changes

2020-06-16 00:03 UTC, calcmogul commented on wpilibc/src/main/native/include/frc/controller/LinearPlantInversionFeedforward.h
> +   * @param r     The reference state of the current timestep(k).
There should be a space before the parentheses.

2020-06-16 00:03 UTC, calcmogul commented on wpilibc/src/main/native/include/frc/controller/LinearPlantInversionFeedforward.h
> +   * @param nextR The reference state of the future timestep(k + dt).
There should be a space before the parentheses.

2020-06-16 00:03 UTC, calcmogul commented on wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ControlAffinePlantInversionFeedforward.java
> +   * @param nextR The reference state of the future timestep(k + dt).
There should be a space before the parentheses.

2020-06-16 00:03 UTC, calcmogul commented on wpilibc/src/main/native/include/frc/controller/ControlAffinePlantInversionFeedforward.h
> +   * @param nextR The reference state of the future timestep(k + dt).
There should be a space before the parentheses.

2020-06-16 00:03 UTC, calcmogul commented on wpilibc/src/main/native/include/frc/controller/ControlAffinePlantInversionFeedforward.h
> +   * @param r     The reference state of the current timestep(k).
There should be a space before the parentheses.

2020-06-16 00:03 UTC, calcmogul commented on wpilibc/src/main/native/include/frc/controller/ControlAffinePlantInversionFeedforward.h
> +   * @param nextR The reference state of the future timestep(k + dt).
There should be a space before the parentheses.

2020-06-16 00:03 UTC, calcmogul commented on wpilibc/src/main/native/include/frc/controller/LinearPlantInversionFeedforward.h
> +   * @param nextR The reference state of the future timestep(k + dt).
There should be a space before the parentheses.

2020-06-17 02:32 UTC, merged

2020-06-18 15:34 UTC, mcm001 commented
Should be merged